server.port = 8081
# --- ??????????? ? Azure PostgreSQL (?? .env ???????? B) ---
# URL (?????) ???? ??????. ?? ????? ??? ?? README ???????? B.
spring.datasource.url=jdbc:postgresql://iotdemo-pg.postgres.database.azure.com:5432/iot_data?sslmode=require
# ????? ? ??????
spring.datasource.username=iotadmin
spring.datasource.password=FireDemo_2024
# ???? ????????? Spring, ????? ??????? ????????????
spring.datasource.driver-class-name=org.postgresql.Driver

# --- ????????? JPA (Spring Data) ---
# ??????? Hibernate (JPA), ? ?????? "????????" SQL ??????????
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ?????: 'validate' 
# Spring ??? ?????? ????????, ??? ???? ?????? @Entity (Telemetry.java, Alarm.java)
# C???????????? ???????? ? ????. ???? ??? - ????? ?????? (??? ??????, ?? ????? ?????? ????????).
# ?? ????????? 'create' ??? 'create-drop' - ??? ?????? ???? ???????? B!
spring.jpa.hibernate.ddl-auto=update

# ?????????? SQL-??????? ? ???????. ??????? ??? ???????.
spring.jpa.show-sql=true

# ?????????, ??? ? ???? ???? ????? "iot"
spring.jpa.properties.hibernate.default_schema=iot

# --- MQTT SETTINGS ---
mqtt.broker.url=tcp://mosquitto:1883

mqtt.client.id=backend-server-client
mqtt.topic=sensor/data
mqtt.username=
mqtt.password=
