name: Deploy IoT System (Distributed - Local Simulator)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Deploy to Separate Servers
        run: |
              ssh-keyscan -H ${{ secrets.BACKEND_API_IP }} >> ~/.ssh/known_hosts || true
              ssh-keyscan -H ${{ secrets.MQTT_BROKER_IP }} >> ~/.ssh/known_hosts || true
              ssh-keyscan -H ${{ secrets.POSTGRES_IP }} >> ~/.ssh/known_hosts || true

              # ---  1: (PostgreSQL) ---
              echo "Restarting PostgreSQL..."
              ssh -o ConnectTimeout=30 -o StrictHostKeyChecking=no dburan@${{ secrets.POSTGRES_IP }} << 'EOF'
              if [ ! -d "IoT-Fire-Detection-and-Safety-System-" ]; then
                git clone https://github.com/anakataa/IoT-Fire-Detection-and-Safety-System-.git
              fi
              cd IoT-Fire-Detection-and-Safety-System-
              
              git pull 

              cd db_init

              sudo docker-compose up -d 

              sudo docker ps
              EOF

              # ---  2:  (MQTT Mosquitto) ---
              echo "Restarting MQTT Broker..."
              ssh -o ConnectTimeout=30 -o StrictHostKeyChecking=no dburan@${{ secrets.MQTT_BROKER_IP }} << 'EOF'
              if [ ! -d "IoT-Fire-Detection-and-Safety-System-" ]; then
                git clone https://github.com/anakataa/IoT-Fire-Detection-and-Safety-System-.git
              fi
              cd IoT-Fire-Detection-and-Safety-System-
              
              git pull 

              cd mqtt-broker

              cd mosquitto-docker

              sudo docker-compose up -d 

              sudo docker ps
              EOF 


              # ---  3: BACKEND API ---
              echo "Updating Backend..."
              ssh -o ConnectTimeout=30 -o StrictHostKeyChecking=no dburan@${{ secrets.BACKEND_API_IP }} << 'EOF'
              if [ ! -d "IoT-Fire-Detection-and-Safety-System-" ]; then
              git clone https://github.com/anakataa/IoT-Fire-Detection-and-Safety-System-.git
              fi
              cd IoT-Fire-Detection-and-Safety-System-

              git pull 

              cd backend-server 

              sudo docker-compose down -v

              ./gradlew clean build -x test

              sudo docker-compose up -d --build

              sudo docker ps 

              sudo docker image prune -f
              EOF


